### ISSUE TITLE
Cannot find viper.json if XDG_CONFIG_HOME not set

### ISSUE THREAD

**Issue by mahmed2000** [0neGal/viper-sh#2]
JSONPATH requires XDG_CONFIG_HOME to be set to read the file on line 6. Needs the same as on line 110

`JSONPATH="$(jq -r .gamepath "$XDG_CONFIG_HOME/viper.json" 2> /dev/null)"`
to
`JSONPATH="$(jq -r .gamepath "${XDG_CONFIG_HOME:-$HOME/.config}/viper.json" 2> /dev/null)"`

**Comment by 0neGal** [comment]
This should be fixed with [`7d52145`](https://github.com/0neGal/viper-sh/commit/7d521458923cb4deaddc2d8ceeaa697d0eb358f8)

I would like to point out that, if you already know the fix to a bug, it would be much better if you simply opened a pull request instead of an issue.
